#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 26 20:45:35 2020

@author: mangsa
"""

import matplotlib.pyplot as plt
import random
import numpy as np
#step 1 on chart
rotations1 = {"InSrv1": 4, "Card1": 4, "Surg": 14, "Emed": 23, "ICU":4 , "OB1": 8, "PedC": 4, "InSrv2": 4, "NICU": 4, "Neuro": 4, "Clinic": 33, "OB2": 2 }
electives = ["InSrv1", "Card1", "Surg", "Emed", "ICU", "OB1", "PedC", "InSrv2", "NICU", "Neuro", "Clinic", "OB2"]
sessions = [4, 4, 14, 23, 4, 8, 4, 4, 4, 4, 33, 2]
z = list(zip(electives, sessions))
#print("The original schedule for resident 1, year 1 is:" + str(rotations1))

#step 2 on chart
def randomShuffle():
    random.shuffle(z)
    electives[:], sessions[:] = zip(*z)
    print("the shuffled rotations are ")
    print(electives, sessions)
    


def quarter():
    firstQuarter = sessions[:len(sessions)//4]
    secondQuarter = sessions[len(sessions)//4:]
    thirdQuarter = sessions[:len(sessions)//4]
    fourthQuarter = sessions[len(sessions)//4:]
    quarterRange = max(firstQuarter) - max(secondQuarter)
    quarterRange1 = max(thirdQuarter) - max(fourthQuarter)
    firstTotal = sum(firstQuarter)
    print ("The sum of the first quarter of sessions is:" + str(firstTotal))
    secondTotal = sum(secondQuarter)
    print ("The sum of the second quarter of sessions is:" + str(secondTotal))
    thirdTotal = sum(thirdQuarter)
    print ("The sum of the third quarter of sessions is:" + str(thirdTotal))
    fourthTotal = sum(fourthQuarter)
    print ("The sum of the fourth quarter of sessions is:" + str(fourthTotal))
    maxFirst = max(firstQuarter)
    print ("The max value of the first quarter is" + str(maxFirst))
    minFirst = min(firstQuarter)       
    print ("The min value of the first quarter is" + str(minFirst))
    maxSecond = max(secondQuarter)
    print ("The max value of the second quarter is" + str(maxSecond))
    minSecond = min(secondQuarter)
    print ("The min value of the second quarter is" + str(minSecond))
    maxThird = max(thirdQuarter)
    print ("The max value of the third quarter is" + str(maxThird))
    minThird = min(thirdQuarter)
    print ("The min value of the third quarter is" + str(minThird))
    maxFourth = max(fourthQuarter)
    print ("The max value of the fourth quarter is" + str(maxFourth))
    minFourth = min(fourthQuarter)
    print ("The min value of the fourth quarter is" + str(minFourth))
    if quarterRange > -10:
            maxFirst, maxSecond = minSecond, minFirst
            maxThird, maxFourth = minThird, minFourth
            print("Check works")
            randomShuffle()
            quarter()
    if quarterRange1 > -10:
            maxFirst, maxSecond = minSecond, minFirst
            maxThird 
            print("Check works")
            randomShuffle()
            quarter()        
    else:
            print("passed check")
            results = firstQuarter + secondQuarter + thirdQuarter + fourthQuarter
            #finalResults = dict(results)
            print("the new schedule is:" + str (results))
            keys = electives
            values = sessions
            plt.bar(keys, values)
           
randomShuffle()
quarter()
